version: '3.6'
services:
  postgres:
    # image: postgres:9.6  only this versin works with konga
    image: postgres:12
    container_name: 'postgres'
    restart: always
    ports:
      - 5432:5432
    volumes:
      # - db_data:/var/lib/postgresql/data
      - ./docker-configs/postgres/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - backend

  hasura:
    image: hasura/graphql-engine:latest
    container_name: 'hasura'
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      # HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: admin
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://192.168.0.10:8900/auth/jwk", "issuer":"hasura-auth"}'
    networks:
      - backend

  kong:
    image: kong:latest
    container_name: 'kong'
    restart: always
    working_dir: /etc/kong
    command: bash -c "kong start -c kong.conf"
    ports:
      - '8000:8000'
      - '8001:8001'
    depends_on:
      - 'postgres'
    networks:
      - backend
    environment:
      KONG_LOG_LEVEL: debug
      KONG_DATABASE: 'off'
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
    volumes:
      - ./docker-configs/kong/kong.yml:/etc/kong/kong.yml
      - ./docker-configs/kong/kong.conf:/etc/kong/kong.conf

volumes:
  db_data:

networks:
  backend:
    external: false
